c3_budget_homepage:
    path:     /
    defaults: { _controller: C3BudgetBundle:Transaction:index }
c3_budget_add_transaction:
    path:     /add/
    defaults: { _controller: C3BudgetBundle:Transaction:add }